import { describe, it, expect } from "vitest";
import * as secp from "@noble/secp256k1";
import {
  calcPaddedLen,
  computeSharedX,
  decryptNip04,
  decryptNip44,
  deriveConversationKey,
  encryptNip04,
  encryptNip44,
  pickEncryptionFromInfoTag,
  NWC_ENCRYPTION_NIP04,
  NWC_ENCRYPTION_NIP44_V2,
} from "../../src/wallets/nwc.js";

// ── NWC encryption crypto: NIP-04 (AES-256-CBC) + NIP-44 v2 (ChaCha20/HKDF) ──
//
// These pin the TS crypto against INDEPENDENT ground truth so a green run proves
// byte-correctness, not merely self-consistency:
//
//   * The BIP340 pubkey / raw shared-X / NIP-04 round-trip vectors are ported
//     from the MCP Python client's test_nwc_coincurve_vectors.py.
//   * The NIP-04 and NIP-44 known-answer payloads (fixed IV / fixed nonce) were
//     GENERATED by the proven MCP Python NWC client (nwc_wallet.py) with
//     coincurve + cryptography, then hardcoded here. A green run proves the TS
//     port (node:crypto ChaCha20/HMAC + @noble ECDH) produces output that is
//     byte-identical to the Python client that is confirmed working against
//     CoinOS (NIP-04) and Alby Hub (NIP-44 v2) in production.

// ── Helpers ──
function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.slice(i, i + 2), 16);
  }
  return bytes;
}
function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// ── Vectors (generated from the MCP Python NWC client — see file header) ──
const SECKEY_3 =
  "0000000000000000000000000000000000000000000000000000000000000003";
const BIP340_PUBKEY_FOR_3 =
  "f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9";
const SECKEY_A =
  "0142424242424242424242424242424242424242424242424242424242424242";
const ALICE_PUB =
  "8dad4bc055b6f9698eaa43c0e3c320f9ca377d6b237671048b50a7920d221224";
// shared-X for ECDH(A, bob_pub) — symmetric, so it also decrypts messages
// addressed to either party.
const SHARED_X =
  "150b9a865720b12157e2f5463189a5da551586e655bb4babba40e05594005551";
const CONVERSATION_KEY =
  "e0f6f2aeb0e50f479fd0da0e7b6965799a0104754d6448f4a7332138add9914d";
const IV16 = "000102030405060708090a0b0c0d0e0f";
const NONCE32 =
  "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";
const PLAINTEXT = "the magic words are squeamish ossifrage";
const NIP04_CIPHERTEXT =
  "6m20/hddxV4krD0M7AllC54Eptvx7tvPyR4X5eatqLooNc+icAf9etlMrqjsuxBB?iv=AAECAwQFBgcICQoLDA0ODw==";
const NIP44_PAYLOAD =
  "AgABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fT/aulO+u59qN09JORRy56fr0mp6XbC+D+xeTWCfjbmL1iG+Esy/F/+oQuwD4Dmds+vvyR23i3tN79c2FoAI7Ob1mpWi2sjzpkrSBzADQ8PKnlmKJFJfV1KbZcrUP4+LMMXY=";
const NIP44_SHORT_PAYLOAD =
  "AgABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fT9C7/IqOirvqurFuMnPLjYnU++zyTFzyjnLyNU6QBkKa++S8f+jhv2DY4r7VJUDJ3CeMnxD/M6YP8wmYCmGiFZ5v";

const sharedX = hexToBytes(SHARED_X);

describe("curve vectors (ported from test_nwc_coincurve_vectors.py)", () => {
  it("derives the canonical BIP340 x-only pubkey for secret scalar 3", () => {
    // @noble schnorr.getPublicKey yields the x-only pubkey the wallet uses.
    expect(bytesToHex(secp.schnorr.getPublicKey(hexToBytes(SECKEY_3)))).toBe(
      BIP340_PUBKEY_FOR_3,
    );
  });

  it("computeSharedX matches the independently-generated raw shared-X (CoinOS path)", () => {
    const got = computeSharedX(hexToBytes(SECKEY_A), BIP340_PUBKEY_FOR_3, secp);
    expect(bytesToHex(got)).toBe(SHARED_X);
    expect(got.length).toBe(32);
  });

  it("computeSharedX is symmetric: ECDH(a,B) == ECDH(b,A)", () => {
    const ab = computeSharedX(hexToBytes(SECKEY_A), BIP340_PUBKEY_FOR_3, secp);
    const ba = computeSharedX(hexToBytes(SECKEY_3), ALICE_PUB, secp);
    expect(bytesToHex(ab)).toBe(bytesToHex(ba));
  });
});

describe("NIP-04 (AES-256-CBC, raw shared-X key)", () => {
  it("KAT: decrypts the Python-generated ciphertext to the known plaintext", async () => {
    expect(await decryptNip04(NIP04_CIPHERTEXT, sharedX)).toBe(PLAINTEXT);
  });

  it("KAT: encrypt with the fixed IV reproduces the Python ciphertext byte-for-byte", async () => {
    const ct = await encryptNip04(PLAINTEXT, sharedX, hexToBytes(IV16));
    expect(ct).toBe(NIP04_CIPHERTEXT);
  });

  it("round-trips with a random IV", async () => {
    const ct = await encryptNip04("hello nip04 世界", sharedX);
    expect(ct).toContain("?iv=");
    expect(await decryptNip04(ct, sharedX)).toBe("hello nip04 世界");
  });

  it("throws on malformed content (no ?iv= separator)", async () => {
    await expect(decryptNip04("not-nip04", sharedX)).rejects.toThrow();
  });
});

describe("NIP-44 v2 (ChaCha20 + HKDF-SHA256 + HMAC)", () => {
  it("derives the NIP-44 conversation key (HKDF-extract, salt='nip44-v2')", () => {
    expect(deriveConversationKey(sharedX).toString("hex")).toBe(
      CONVERSATION_KEY,
    );
  });

  it("KAT: decrypts the Python-generated payload to the known plaintext", () => {
    expect(decryptNip44(NIP44_PAYLOAD, sharedX)).toBe(PLAINTEXT);
  });

  it("KAT: encrypt with the fixed nonce reproduces the Python payload byte-for-byte", () => {
    expect(encryptNip44(PLAINTEXT, sharedX, hexToBytes(NONCE32))).toBe(
      NIP44_PAYLOAD,
    );
  });

  it("KAT: single-char plaintext padded to 32 bytes matches Python", () => {
    expect(decryptNip44(NIP44_SHORT_PAYLOAD, sharedX)).toBe("a");
    expect(encryptNip44("a", sharedX, hexToBytes(NONCE32))).toBe(
      NIP44_SHORT_PAYLOAD,
    );
  });

  it("round-trips a longer unicode message with a random nonce", () => {
    const msg = "x".repeat(500) + " — δοκιμή";
    const payload = encryptNip44(msg, sharedX);
    expect(Buffer.from(payload, "base64")[0]).toBe(0x02); // version byte
    expect(decryptNip44(payload, sharedX)).toBe(msg);
  });

  it("rejects a tampered payload (HMAC verification fails)", () => {
    const bytes = Buffer.from(NIP44_PAYLOAD, "base64");
    // Flip a bit in the ciphertext region (after version+nonce, before mac).
    bytes[40] ^= 0x01;
    expect(() => decryptNip44(bytes.toString("base64"), sharedX)).toThrow(
      /HMAC/i,
    );
  });

  it("rejects an unsupported version byte", () => {
    const bytes = Buffer.from(NIP44_PAYLOAD, "base64");
    bytes[0] = 0x01;
    expect(() => decryptNip44(bytes.toString("base64"), sharedX)).toThrow(
      /version/i,
    );
  });
});

describe("calcPaddedLen (NIP-44 padding buckets)", () => {
  it.each([
    [1, 32],
    [16, 32],
    [32, 32],
    [33, 64],
    [100, 128],
    [320, 320],
  ])("pads %i bytes to %i", (input, expected) => {
    expect(calcPaddedLen(input)).toBe(expected);
  });

  it("rejects non-positive lengths", () => {
    expect(() => calcPaddedLen(0)).toThrow();
  });
});

describe("pickEncryptionFromInfoTag (NIP-47 INFO auto-detect)", () => {
  it("falls back to nip04 for empty/missing tag", () => {
    expect(pickEncryptionFromInfoTag(null)).toBe(NWC_ENCRYPTION_NIP04);
    expect(pickEncryptionFromInfoTag(undefined)).toBe(NWC_ENCRYPTION_NIP04);
    expect(pickEncryptionFromInfoTag("")).toBe(NWC_ENCRYPTION_NIP04);
  });

  it("picks nip44_v2 when advertised (space- or comma-separated)", () => {
    expect(pickEncryptionFromInfoTag("nip04 nip44_v2")).toBe(
      NWC_ENCRYPTION_NIP44_V2,
    );
    expect(pickEncryptionFromInfoTag("nip04,nip44_v2")).toBe(
      NWC_ENCRYPTION_NIP44_V2,
    );
    expect(pickEncryptionFromInfoTag("NIP44_V2")).toBe(
      NWC_ENCRYPTION_NIP44_V2,
    );
  });

  it("picks nip04 when only nip04 is advertised", () => {
    expect(pickEncryptionFromInfoTag("nip04")).toBe(NWC_ENCRYPTION_NIP04);
  });

  it("falls back to nip04 for an unknown scheme", () => {
    expect(pickEncryptionFromInfoTag("some_future_scheme")).toBe(
      NWC_ENCRYPTION_NIP04,
    );
  });
});
